### PR TITLE
add: Homepage styles and structure

### PR DESCRIPTION
**Pull request by Varu98**
Created :-
- HomePage
- Navbar
- ProductCard

Add data to Product.js in db folder

### CODE REVIEW

**Comment by Varu98** [comment]
recording


<details><summary>Browser metadata</summary>





```
Path:      /
Browser:   Chrome 97.0.4692.71 on Linux x86_64
Viewport:  1920 x 968 @1x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--verdant-sorbet-e08b2e.netlify.app%2F&os=OS%20X&os_version=Big%20Sur&browser=Chrome&browser_version=97.0&resolution=1920x968&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-1--verdant-sorbet-e08b2e.netlify.app/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6251276f11c775546906f293&commentID=625128870d4145662d1f02a5&resolution=resolved)

**Comment by Varu98** [comment]
Deploy Preview :- 
https://deploy-preview-1--verdant-sorbet-e08b2e.netlify.app/
<details><summary>Browser metadata</summary>





```
Path:      /
Browser:   Chrome 97.0.4692.71 on Linux x86_64
Viewport:  1920 x 968 @1x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--verdant-sorbet-e08b2e.netlify.app%2F&os=OS%20X&os_version=Big%20Sur&browser=Chrome&browser_version=97.0&resolution=1920x968&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-1--verdant-sorbet-e08b2e.netlify.app/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6251276f11c775546906f293&commentID=625128ce0d4145662d1f02b3&resolution=resolved)

**Review by manojasarsa — APPROVED** [review]
Good to merge!

**Review by bipin7yadav — APPROVED** [review]
good to merge

**Review by gopalbbharadva — APPROVED** [review]
Give cursor : pointer on button or card hover ,else everything is good.

**Pull request merged**
